### ISSUE TITLE
Problem after upgrading from 0.2.9

### ISSUE THREAD

**Issue by kfilios** [Karthik-B-06/react-native-segmented-control#42]
After upgrading to 1.1.2 from 0.2.9 I receive the following errors:

 ERROR  TypeError: _ReanimatedModule.default.configureProps is not a function. (In '_ReanimatedModule.default.configureProps(Object.keys(NATIVE_THREAD_PROPS_WHITELIST), Object.keys(UI_THREAD_PROPS_WHITELIST))', '_ReanimatedModule.default.configureProps' is undefined)
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.

I have react-native-reanimated 2.1.0 and react-native-gesture-handler 2.3.2 installed and developing in iOS only.

I couldn't find any solution. Do you have any idea of what could cause this issue?

Thanks in advance!

**Comment by Karthik-B-06** [comment]
Thanks for raising the issue, @kfilios I will look into it.

**Comment by denissdubinin** [comment]
Getting same issue
```
    "react": "17.0.2",
    "react-native": "0.68.1",
    "react-native-gesture-handler": "^2.4.2",
    "react-native-reanimated": "^2.8.0",
    "rn-segmented-control": "^1.1.2"
```

**Comment by Temkit** [comment]
same here

**Comment by mberatsanli** [comment]
adjust "resoulutions" key in the package.json, the run yarn start again.

```
  "resolutions": {
    "react-native-reanimated": "^2.9.1"
  },
```

**Comment by Tauka** [comment]
Is it not fixed yet? I can't use this library

**Comment by exotexot** [comment]
This module is broken and cannot co-exist alongside other installed versions with gesture handler and reanimated.

Can pls someone fix this.

**Comment by whatdtech** [comment]
**https://github.com/whatdtech/react-native-segmented-control**

this is a modified version of this fork installation details are in readme file. works with latest expo and bare react native .70 version
